# Generated by Django 3.0.7 on 2020-09-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Info',
        ),
    ]
